# Generated by Django 4.2.5 on 2023-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='payment_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='payment_type',
            field=models.CharField(choices=[('transfer_money', 'Pul kochirish'), ('by_card', 'Plastik karta'), ('cash', 'Naqd pul')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_moderation', 'Moderatsiyada'), ('confirmed', 'Tasdiqlangan'), ('denied', 'Rad qilingan')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('legal_entity', 'Yuridik shaxs'), ('individual_person', 'Jismoniy shaxs')], max_length=20),
        ),
    ]
